-- 1) 보호자 & 아이
CREATE TABLE guardian (
  guardian_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               VARCHAR2(100) NOT NULL,
  phone              VARCHAR2(32)  NOT NULL,
  email              VARCHAR2(254),
  notification_pref  VARCHAR2(16)  DEFAULT 'sms' CHECK (notification_pref IN ('sms','push','both')),
  created_at         TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
);

CREATE TABLE infant (
  infant_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guardian_id  NUMBER(19) NOT NULL,
  name         VARCHAR2(100) NOT NULL,
  birth_date   DATE,
  gender       VARCHAR2(16) CHECK (gender IN ('male','female','other')),
  created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  updated_at   TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT fk_infant_guardian FOREIGN KEY (guardian_id) REFERENCES guardian(guardian_id)
);

CREATE INDEX idx_infant_guardian ON infant(guardian_id);

-- 2) 업로드 음성 파일 메타
CREATE TABLE audio_file (
  audio_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  infant_id    NUMBER(19) NOT NULL,
  upload_time  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  storage_uri  VARCHAR2(512) NOT NULL,
  duration_ms  NUMBER(10),
  sample_rate  NUMBER(10),
  file_hash    VARCHAR2(128),
  deleted_at   TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT fk_audio_infant FOREIGN KEY (infant_id) REFERENCES infant(infant_id)
);

CREATE INDEX idx_audio_infant_time ON audio_file(infant_id, upload_time);

-- 3) 모델 추론 로그(분류/원인 예측 공용)
CREATE TABLE model_inference (
  inference_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audio_id      NUMBER(19) NOT NULL,
  model_type    VARCHAR2(16) NOT NULL CHECK (model_type IN ('classifier','cause')),
  model_version VARCHAR2(64) NOT NULL,
  pred_label    VARCHAR2(64),
  pred_scores   CLOB CHECK (pred_scores IS JSON), -- 21c라서 CLOB + IS JSON 사용 가능
  latency_ms    NUMBER(10),
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_infer_audio FOREIGN KEY (audio_id)
    REFERENCES audio_file(audio_id)
);

CREATE INDEX idx_infer_audio ON model_inference(audio_id);
CREATE INDEX idx_infer_type_time ON model_inference(model_type, created_at);

-- 4) 울음 이벤트
CREATE TABLE cry_event (
  event_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  infant_id   NUMBER(19) NOT NULL,
  event_time  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  duration_ms NUMBER(10),
  confidence  NUMBER(5,2),
  severity VARCHAR2(16),
  cry_type    VARCHAR2(32),
  detected_by VARCHAR2(32) DEFAULT 'model',
  is_resolved CHAR(1) DEFAULT 'N' CHECK (is_resolved IN ('Y','N')),
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_event_infant FOREIGN KEY (infant_id)
    REFERENCES infant(infant_id)
);

CREATE INDEX idx_event_infant_time ON cry_event(infant_id, event_time);
CREATE INDEX idx_event_type_time ON cry_event(cry_type, event_time);

-- 5) 보호자 조치 로그
CREATE TABLE action_log (
  action_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      NUMBER(19) NOT NULL,
  action_type   VARCHAR2(32) NOT NULL,
  action_detail VARCHAR2(4000),
  result        VARCHAR2(32),
  executed_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_action_event FOREIGN KEY (event_id)
    REFERENCES cry_event(event_id)
);

CREATE INDEX idx_action_event_time ON action_log(event_id, executed_at);

-- 6) 알림 이력
CREATE TABLE notification_log (
  notification_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id        NUMBER(19) NOT NULL,
  guardian_id     NUMBER(19) NOT NULL,
  channel         VARCHAR2(16) NOT NULL
                    CHECK (channel IN ('sms','push','both')),
  sent_at         TIMESTAMP(6) WITH TIME ZONE,
  status          VARCHAR2(16)
                    CHECK (status IN ('sent','failed','queued')),
  provider_msg_id VARCHAR2(128),
  latency_ms      NUMBER(10),
  CONSTRAINT fk_notif_event FOREIGN KEY (event_id)
    REFERENCES cry_event(event_id),
  CONSTRAINT fk_notif_guardian FOREIGN KEY (guardian_id)
    REFERENCES guardian(guardian_id)
);

CREATE INDEX idx_notif_event ON notification_log(event_id);
CREATE INDEX idx_notif_guardian_time ON notification_log(guardian_id, sent_at);

-- 7) 리포트/패턴 (요약 테이블)
CREATE TABLE report (
  report_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  infant_id    NUMBER(19) NOT NULL,
  period_start TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  period_end   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  report_type  VARCHAR2(16) CHECK (report_type IN ('daily','weekly','monthly')),
  summary      CLOB,
  file_url     VARCHAR2(512),
  created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_report_infant FOREIGN KEY (infant_id) REFERENCES infant(infant_id)
);

CREATE INDEX idx_report_infant_period ON report(infant_id, period_start);

CREATE TABLE pattern_analysis (
  pattern_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  infant_id           NUMBER(19) NOT NULL,
  time_slot           VARCHAR2(16),
  frequency           NUMBER(10),
  avg_duration_ms     NUMBER(10),
  predicted_next_time TIMESTAMP(6) WITH TIME ZONE,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_pattern_infant FOREIGN KEY (infant_id) REFERENCES infant(infant_id)
);

CREATE INDEX idx_pattern_infant_slot ON pattern_analysis(infant_id, time_slot);
